apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: front-test
  description: Servicio backend
  links:
    - url: https://test.com
      title: Backend Prod
      icon: dashboard
  tags:
    - nodejs
  annotations:
    sonarqube.org/project-key: 'Sonar/com.insignias.backend'
spec:
  type: service
  lifecycle: production
  owner: sebastianacevedo91
  system: test
  dependsOn:
    - Resource:bd-postgres   
